name: Python CI

on:
    push: 
        branches: 
            - main
    pull_request:
        branches: 
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # step 1 : checkout code from repository
            - name: Check Out Code
              uses: actions/checkout@v2

            # step 2 : setup python
            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            
            # step 3 : install dependencies
            - name: Install Dependencies
              run: python install -r requirements.txt

            # step 4 : run tests
            - name: Run test cases
              run: pytest
